server:
  port: 8083

spring:
  application:
    name: WS-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
      

rabbitmq:
  #host: 52.91.64.102
  host: localhost
  port: 61613
  username: guest
  password: guest